import type { Sha256Digest, VisualEvidence } from "../brand-read/StudioBrandReadClient";

export type PacketTrustState = "local-current" | "context-matched-external" | "self-consistent-external" | "context-stale" | "context-mismatch" | "invalid";
export type ProposalKind = "evidence-only" | "derive" | "qa-baseline" | "consumer-install" | "consumer-sync" | "export";
export type CandidateDisposition = "unreviewed" | "preferred" | "approved" | "rejected" | "needs-revision" | "deferred";
export type ClaimCategory = "composition" | "alignment" | "spacing" | "legibility" | "contrast" | "color" | "brand-fit" | "accessibility" | "small-size" | "technical" | "other";
export type ClaimSeverity = "note" | "minor" | "substantive" | "blocking";
export interface PacketContext { readonly corePackageVersion: "0.4.0"; readonly studioVersion: "0.1.0"; readonly studioProtocolVersion: "1.2"; readonly project: { readonly label?: string; readonly canonicalDigest: Sha256Digest; readonly brandSystemDigest: Sha256Digest }; readonly source?: { readonly packageId: string; readonly brandVersion: string; readonly brandSystemDigest: Sha256Digest } }
export type TargetSelector = { readonly kind: "asset"; readonly assetId: string } | { readonly kind: "binding"; readonly family: string; readonly role: string; readonly variant: string };
export interface DesignTarget { readonly targetId: string; readonly selector: TargetSelector; readonly canonicalAssetDigest: Sha256Digest; readonly svgDigest: Sha256Digest; readonly purpose: string }
export interface Material { readonly kind: "user-supplied" | "tfsb-rendered" | "third-party" | "external-claim"; readonly identifier: string; readonly digest: Sha256Digest; readonly licenseExpression?: string; readonly noticeDigest?: Sha256Digest }
export interface BriefPacket { readonly schema: "tfsb.design-brief"; readonly schemaVersion: 1; readonly briefId: string; readonly revision: number; readonly title: string; readonly objective: string; readonly context: PacketContext; readonly targets: readonly DesignTarget[]; readonly constraints: { readonly allowedProposalKinds: readonly ProposalKind[]; readonly requiredTokenIds: readonly string[]; readonly requiredRecipeIds: readonly string[]; readonly qaProfileIds: readonly string[]; readonly renderTuples: readonly { readonly width: number; readonly height: number; readonly background: string }[]; readonly acceptanceCriteria: readonly string[]; readonly prohibitedChanges: readonly string[] }; readonly materials: readonly Material[]; readonly visualEvidence: readonly VisualEvidence[]; readonly briefDigest: Sha256Digest }
export type Proposal =
  | { readonly kind: "evidence-only" }
  | { readonly kind: "derive"; readonly selection: { readonly kind: "all" } | { readonly kind: "recipes"; readonly recipeIds: readonly string[] } }
  | { readonly kind: "qa-baseline"; readonly profileId: string; readonly caseId: string }
  | { readonly kind: "consumer-install"; readonly sourcePackages: readonly SourcePackage[]; readonly profileIds: readonly string[]; readonly parameters: readonly ParameterSet[] }
  | { readonly kind: "consumer-sync"; readonly sourcePackages: readonly SourcePackage[]; readonly profileIds?: readonly string[]; readonly parameters?: readonly ParameterSet[] }
  | { readonly kind: "export"; readonly profileId: string; readonly outputIds?: readonly string[] };
export interface SourcePackage { readonly packageId: string; readonly brandVersion: string; readonly brandSystemDigest: Sha256Digest }
export interface ParameterSet { readonly profileId: string; readonly values: readonly { readonly parameter: string; readonly value: string }[] }
export interface CandidatePacket { readonly schema: "tfsb.design-candidate"; readonly schemaVersion: 1; readonly briefDigest: Sha256Digest; readonly candidateId: string; readonly revision: number; readonly revisionOf?: Sha256Digest; readonly author: { readonly kind: "human" | "agent" | "tool"; readonly label: string; readonly toolName?: string; readonly toolVersion?: string }; readonly title: string; readonly rationale: string; readonly proposal: Proposal; readonly claims: readonly { readonly category: ClaimCategory; readonly severity: ClaimSeverity; readonly message: string }[]; readonly qaSummary: { readonly status: "pass" | "fail" | "skipped" | "unavailable" | "error"; readonly qaResultDigest?: Sha256Digest }; readonly materials: readonly Material[]; readonly visualEvidence: readonly VisualEvidence[]; readonly candidateDigest: Sha256Digest }
export type AnnotationScope = { readonly kind: "artifact" } | { readonly kind: "region"; readonly xMillionths: number; readonly yMillionths: number; readonly widthMillionths: number; readonly heightMillionths: number };
export interface ReviewAnnotation { readonly annotationId: string; readonly candidateDigest: Sha256Digest; readonly visualEvidenceDigest: Sha256Digest; readonly artifactRole: "current" | "baseline" | "before" | "after"; readonly pngDigest: Sha256Digest; readonly scope: AnnotationScope; readonly category: ClaimCategory; readonly severity: ClaimSeverity; readonly comment: string; readonly elementId?: string }
export interface ReviewPacket { readonly schema: "tfsb.design-review"; readonly schemaVersion: 1; readonly briefDigest: Sha256Digest; readonly candidateDigests: readonly Sha256Digest[]; readonly previousReviewDigest?: Sha256Digest; readonly annotations: readonly ReviewAnnotation[]; readonly dispositions: readonly { readonly candidateDigest: Sha256Digest; readonly disposition: CandidateDisposition }[]; readonly overallDisposition: { readonly kind: "no-decision" | "rejected-all" } | { readonly kind: "preferred" | "approved" | "needs-revision"; readonly candidateDigest: Sha256Digest }; readonly summary: string; readonly reviewDigest: Sha256Digest }
export type DesignEvidencePacket = BriefPacket | CandidatePacket | ReviewPacket;
export type PacketKind = "brief" | "candidate" | "review";
