import type {
  AssetIdentity, BrandFamily, BrandStatus, BrandToken, ConsumerLockStatus, ConsumerProfile, ConsumerProfilePage,
  DiffChange, DiffValue, ExportCapability, ExportStatus, ExportStatusPage, FamilyPage, Page, QaCase, QaTargetSelector,
  QaDiagnostic, QaJsonValue, QaProfile, QaProfilePage, QaResult, RecipeGraph, SemanticDiff,
  Sha256Digest, TokenPage, VisualArtifact, VisualEvidence, VisualRole,
} from "./StudioBrandReadClient";

export class StudioBrandReadValidationError extends Error {
  constructor() { super("Studio brand read returned an invalid typed response"); this.name = "StudioBrandReadValidationError"; }
}

const DIGEST = /^sha256:[a-f0-9]{64}$/u;
const ID = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/u;
const ROLE = /^(?:[a-z][a-z0-9]*(?:-[a-z0-9]+)*|x\.[a-z][a-z0-9]*(?:-[a-z0-9]+)*\.[a-z][a-z0-9]*(?:-[a-z0-9]+)*)$/u;
const PUBLIC_ID = /^[A-Za-z0-9][A-Za-z0-9._:/-]{0,255}$/u;
const QUALIFIED_RASTER_ID = "sha256:4bb08e677b87ef1ca74c35c5c22f547cebef4c22a1f98a08a9246fd9397d0f11";
const forbiddenKeys = new Set(["sessionNonce", "requestId", "canonicalSvg", "svgBytes", "baselinePath", "companionText", "receiptJson", "rendererPath", "modulePath", "packagePath"]);

type Rec = Record<string, unknown>;
type DecoderValue = null | boolean | number | string | readonly DecoderValue[] | { readonly [key: string]: DecoderValue };

function record(value: unknown): Rec { if (typeof value !== "object" || value === null || Array.isArray(value)) fail(); return value as Rec; }
function exact(value: unknown, required: readonly string[], optional: readonly string[] = []): Rec {
  const item = record(value); const actual = Object.keys(item); const allowed = new Set([...required, ...optional]);
  if (required.some((key) => !Object.hasOwn(item, key)) || actual.some((key) => !allowed.has(key)) || actual.length !== required.length + optional.filter((key) => Object.hasOwn(item, key)).length) fail();
  return item;
}
function fail(): never { throw new StudioBrandReadValidationError(); }
function bool(value: unknown): boolean { if (typeof value !== "boolean") fail(); return value; }
function integer(value: unknown, maximum = Number.MAX_SAFE_INTEGER, minimum = 0): number { if (!Number.isSafeInteger(value) || (value as number) < minimum || (value as number) > maximum) fail(); return value as number; }
function string(value: unknown, maximum = 16_384): string { if (typeof value !== "string" || new TextEncoder().encode(value).length > maximum || value.includes("\0") || value.startsWith("/") || value.includes("/Users/") || value.includes(".tfsb/brand-baselines/")) fail(); return value; }
function enumeration<T extends string>(value: unknown, values: readonly T[]): T { const text = string(value, 256); if (!values.includes(text as T)) fail(); return text as T; }
function id(value: unknown, role = false): string { const text = string(value, 256); if (!(role ? ROLE : ID).test(text)) fail(); return text; }
function publicId(value: unknown): string { const text = string(value, 256); if (!PUBLIC_ID.test(text)) fail(); return text; }
function digest(value: unknown): Sha256Digest { const text = string(value, 71); if (!DIGEST.test(text)) fail(); return text as Sha256Digest; }
function nullableDigest(value: unknown): Sha256Digest | null { return value === null ? null : digest(value); }
function strings<T extends string = string>(value: unknown, max: number, validate: (entry: unknown) => T = string as (entry: unknown) => T): readonly T[] { if (!Array.isArray(value) || value.length > max) fail(); return Object.freeze(value.map(validate)); }
function orderedUnique(values: readonly string[]): void { for (let index = 1; index < values.length; index += 1) if ((values[index - 1] as string) >= (values[index] as string)) fail(); }
function unwrap(raw: unknown, kind: string): unknown { const response = exact(raw, ["data", "kind"]); if (response.kind !== kind) fail(); return response.data; }

function safe(value: unknown, depth = 0): DecoderValue {
  if (depth > 20) fail();
  if (value === null || typeof value === "boolean") return value;
  if (typeof value === "number") { if (!Number.isSafeInteger(value)) fail(); return value; }
  if (typeof value === "string") return string(value);
  if (Array.isArray(value)) { if (value.length > 4_096) fail(); return Object.freeze(value.map((entry) => safe(entry, depth + 1))); }
  const item = record(value); if (Object.keys(item).length > 512) fail();
  const result: Record<string, DecoderValue> = {};
  for (const [key, entry] of Object.entries(item)) { if (!/^[A-Za-z][A-Za-z0-9]*$/u.test(key) || forbiddenKeys.has(key)) fail(); result[key] = safe(entry, depth + 1); }
  return Object.freeze(result);
}

function page<T>(data: unknown, validateItem: (entry: unknown) => T, key: (entry: T) => string): Page<T> {
  const root = exact(data, ["page", "viewDigest"]); const value = exact(root.page, ["size", "count", "items", "nextCursor"]);
  const size = integer(value.size, 128, 1); const count = integer(value.count, size); if (!Array.isArray(value.items) || value.items.length !== count) fail();
  const items = Object.freeze(value.items.map(validateItem)); const keys = items.map(key); orderedUnique(keys);
  const nextCursor = value.nextCursor === null ? null : string(value.nextCursor, 16_384); if ((count < size && nextCursor !== null) || (count === 0 && nextCursor !== null)) fail();
  return Object.freeze({ page: Object.freeze({ size, count, items, nextCursor }), viewDigest: digest(root.viewDigest) });
}

export function validateAssetIdentity(raw: unknown): AssetIdentity {
  const value = exact(unwrap(raw, "asset-identity"), ["assetId", "canonicalAssetDigest", "svgDigest"]);
  return Object.freeze({ assetId: id(value.assetId), canonicalAssetDigest: digest(value.canonicalAssetDigest), svgDigest: digest(value.svgDigest) });
}

export function validateBrandStatus(raw: unknown): BrandStatus {
  const data = record(unwrap(raw, "status"));
  if (data.present === false) { const root = exact(data, ["present", "raster"]); const raster = exact(root.raster, ["available"]); return Object.freeze({ present: false, raster: Object.freeze({ available: bool(raster.available) }) }); }
  const root = exact(data, ["present", "schemaVersion", "brandDigest", "brandSystemDigest", "domains", "counts", "completeness", "derived", "consumerLock", "export", "raster"]);
  if (root.present !== true || root.schemaVersion !== 1 || !Array.isArray(root.domains) || root.domains.length > 7) fail();
  const domains = Object.freeze(root.domains.map((entry) => { const item = exact(entry, ["domain", "state", "digest"]); return Object.freeze({ domain: string(item.domain, 64), state: string(item.state, 64), digest: nullableDigest(item.digest) }); })); orderedUnique(domains.map((entry) => entry.domain));
  const counts = exact(root.counts, ["families", "roles", "variants", "bindings", "requirements", "tokens", "recipes", "qaProfiles", "qaCases", "qaBaselines", "consumerProfiles", "exportProfiles"]);
  const countBounds: Record<string, number> = { families: 32, roles: 64, variants: 256, bindings: 1024, requirements: 256, tokens: 256, recipes: 128, qaProfiles: 32, qaCases: 512, qaBaselines: 256, consumerProfiles: 32, exportProfiles: 32 };
  const typedCounts = Object.fromEntries(Object.entries(countBounds).map(([key, max]) => [key, integer(counts[key], max)])) as BrandStatus extends { present: true; counts: infer T } ? T : never;
  const completeness = exact(root.completeness, ["satisfied", "familyCount", "variantCount", "bindingCount", "requirementCount"]);
  const derivedRaw = record(root.derived); if (Object.keys(derivedRaw).length > 16) fail(); const derived: Record<string, number> = {}; for (const key of Object.keys(derivedRaw).sort()) derived[id(key)] = integer(derivedRaw[key], 128);
  const lock = exact(root.consumerLock, ["present", "status", "packages", "profiles", "mappings"]); const exported = exact(root.export, ["outputs", "receipts"]); const raster = exact(root.raster, ["available"]);
  return Object.freeze({ present: true, schemaVersion: 1, brandDigest: digest(root.brandDigest), brandSystemDigest: nullableDigest(root.brandSystemDigest), domains, counts: Object.freeze(typedCounts), completeness: Object.freeze({ satisfied: bool(completeness.satisfied), familyCount: integer(completeness.familyCount, 32), variantCount: integer(completeness.variantCount, 256), bindingCount: integer(completeness.bindingCount, 1024), requirementCount: integer(completeness.requirementCount, 256) }), derived: Object.freeze(derived), consumerLock: Object.freeze({ present: bool(lock.present), status: string(lock.status, 64), packages: integer(lock.packages, 8), profiles: integer(lock.profiles, 8), mappings: integer(lock.mappings, 512) }), export: Object.freeze({ outputs: integer(exported.outputs, 128), receipts: integer(exported.receipts, 128) }), raster: Object.freeze({ available: bool(raster.available) }) });
}

function family(value: unknown): BrandFamily {
  const item = exact(value, ["id", "name", "requiredRoles", "optionalRoles", "variants", "bindings", "requirements", "complete"]); const familyId = id(item.id); const requiredRoles = strings(item.requiredRoles, 64, (entry) => id(entry, true)); const optionalRoles = strings(item.optionalRoles, 64, (entry) => id(entry, true)); orderedUnique(requiredRoles); orderedUnique(optionalRoles);
  if (!Array.isArray(item.variants) || item.variants.length > 256 || !Array.isArray(item.bindings) || item.bindings.length > 1024 || !Array.isArray(item.requirements) || item.requirements.length > 256) fail();
  const variants = Object.freeze(item.variants.map((entry) => { const variant = exact(entry, ["family", "id", "backgrounds", "colorMode", "scale", "status"], ["minimumWidthPx", "minimumHeightPx", "displayOrder"]); if (id(variant.family) !== familyId) fail(); const backgrounds = strings<"any" | "light" | "dark" | "transparent">(variant.backgrounds, 4, (part) => enumeration(part, ["any", "light", "dark", "transparent"])); return Object.freeze({ family: familyId, id: id(variant.id), backgrounds, colorMode: enumeration(variant.colorMode, ["full-color", "monochrome", "reversed"]), scale: enumeration(variant.scale, ["standard", "simplified"]), status: enumeration(variant.status, ["primary", "secondary"]), ...(variant.minimumWidthPx === undefined ? {} : { minimumWidthPx: integer(variant.minimumWidthPx, 16_384, 1) }), ...(variant.minimumHeightPx === undefined ? {} : { minimumHeightPx: integer(variant.minimumHeightPx, 16_384, 1) }), ...(variant.displayOrder === undefined ? {} : { displayOrder: integer(variant.displayOrder, 65_535) }) }); })); orderedUnique(variants.map((entry) => entry.id));
  const bindings = Object.freeze(item.bindings.map((entry) => { const binding = exact(entry, ["family", "role", "variant", "asset", "authority"], ["derivedState"]); if (id(binding.family) !== familyId) fail(); return Object.freeze({ family: familyId, role: id(binding.role, true), variant: id(binding.variant), asset: id(binding.asset), authority: enumeration(binding.authority, ["source", "derived"]), ...(binding.derivedState === undefined ? {} : { derivedState: string(binding.derivedState, 64) }) }); })); orderedUnique(bindings.map((entry) => `${entry.role}\0${entry.variant}\0${entry.asset}`));
  const requirements = Object.freeze(item.requirements.map((entry) => { const requirement = exact(entry, ["family", "role"], ["background", "colorMode", "scale"]); if (id(requirement.family) !== familyId) fail(); return Object.freeze({ family: familyId, role: id(requirement.role, true), ...(requirement.background === undefined ? {} : { background: enumeration(requirement.background, ["any", "light", "dark", "transparent"]) }), ...(requirement.colorMode === undefined ? {} : { colorMode: enumeration(requirement.colorMode, ["full-color", "monochrome", "reversed"]) }), ...(requirement.scale === undefined ? {} : { scale: enumeration(requirement.scale, ["standard", "simplified"]) }) }); }));
  return Object.freeze({ id: familyId, name: string(item.name, 256), requiredRoles, optionalRoles, variants, bindings, requirements, complete: bool(item.complete) });
}
export function validateFamilyPage(raw: unknown): FamilyPage { return page(unwrap(raw, "family-page"), family, (entry) => entry.id); }

function token(value: unknown): BrandToken {
  const item = record(value); const common = ["id", "type", "referenceCount", "recipeUseCount", "unused"] as const; const tokenId = id(item.id); const referenceCount = integer(item.referenceCount, 1024); const recipeUseCount = integer(item.recipeUseCount, 128); const unused = bool(item.unused); if (unused !== (referenceCount === 0 && recipeUseCount === 0)) fail();
  if (item.type === "color") { exact(item, [...common, "value"]); const color = string(item.value, 9); if (!/^#[0-9A-F]{8}$/u.test(color)) fail(); return Object.freeze({ id: tokenId, type: "color", value: color, referenceCount, recipeUseCount, unused }); }
  if (item.type === "gradient") { exact(item, [...common, "kind", "units", "x1", "y1", "x2", "y2", "stops"]); if (item.kind !== "linear" || !Array.isArray(item.stops) || item.stops.length < 2 || item.stops.length > 16) fail(); const stops = Object.freeze(item.stops.map((entry) => { const stop = exact(entry, ["offset"], ["colorToken", "color"]); if ((stop.colorToken === undefined) === (stop.color === undefined)) fail(); const color = stop.color === undefined ? undefined : string(stop.color, 9); if (color !== undefined && !/^#[0-9A-F]{8}$/u.test(color)) fail(); return Object.freeze({ offset: integer(stop.offset, 1_000_000), ...(stop.colorToken === undefined ? {} : { colorToken: id(stop.colorToken) }), ...(color === undefined ? {} : { color }) }); })); return Object.freeze({ id: tokenId, type: "gradient", kind: "linear", units: enumeration(item.units, ["object-bounding-box-millionth", "user-space"]), x1: integer(item.x1, 16_384_000_000, -16_384_000_000), y1: integer(item.y1, 16_384_000_000, -16_384_000_000), x2: integer(item.x2, 16_384_000_000, -16_384_000_000), y2: integer(item.y2, 16_384_000_000, -16_384_000_000), stops, referenceCount, recipeUseCount, unused }); }
  if (item.type === "dimension") { exact(item, [...common, "unit", "value"]); return Object.freeze({ id: tokenId, type: "dimension", unit: enumeration(item.unit, ["px", "percent-millionth", "viewbox-millionth"]), value: integer(item.value, 16_384_000_000, -16_384_000_000), referenceCount, recipeUseCount, unused }); }
  if (item.type === "opacity") { exact(item, [...common, "value"]); return Object.freeze({ id: tokenId, type: "opacity", value: integer(item.value, 1_000_000), referenceCount, recipeUseCount, unused }); }
  return fail();
}
export function validateTokenPage(raw: unknown): TokenPage { return page(unwrap(raw, "token-page"), token, (entry) => entry.id); }

export function validateRecipeGraph(raw: unknown): RecipeGraph {
  const root = exact(unwrap(raw, "recipe-graph"), ["recipeDigest", "graphDigest", "nodes", "affectedTargetCount", "ownershipConflicts"]); if (!Array.isArray(root.nodes) || root.nodes.length > 128) fail();
  const nodes = Object.freeze(root.nodes.map((entry) => { const node = exact(entry, ["recipeId", "sourceAsset", "targetAsset", "dependencies", "dependents", "operations", "operationDigest", "depth", "targetState", "receiptDigest"]); const dependencies = strings(node.dependencies, 128, id); const dependents = strings(node.dependents, 128, id); orderedUnique(dependencies); orderedUnique(dependents); return Object.freeze({ recipeId: id(node.recipeId), sourceAsset: id(node.sourceAsset), targetAsset: id(node.targetAsset), dependencies, dependents, operations: strings(node.operations, 16, (value) => string(value, 64)), operationDigest: digest(node.operationDigest), depth: integer(node.depth, 8), targetState: string(node.targetState, 64), receiptDigest: nullableDigest(node.receiptDigest) }); })); orderedUnique(nodes.map((entry) => entry.recipeId));
  return Object.freeze({ recipeDigest: digest(root.recipeDigest), graphDigest: digest(root.graphDigest), nodes, affectedTargetCount: integer(root.affectedTargetCount, 128), ownershipConflicts: integer(root.ownershipConflicts, 128) });
}

function qaProfileDescriptor(value: unknown) { const item = exact(value, ["id", "renderer", "formats", "cases"]); const cases = strings(item.cases, 512, id); orderedUnique(cases); return Object.freeze({ id: id(item.id), renderer: enumeration(item.renderer, ["optional", "required"]), formats: strings<"html" | "json" | "markdown">(item.formats, 3, (entry) => enumeration(entry, ["html", "json", "markdown"])), cases }); }
function selector(item: Rec): QaTargetSelector { return { ...(item.asset === undefined ? {} : { asset: id(item.asset) }), ...(item.family === undefined ? {} : { family: id(item.family) }), ...(item.role === undefined ? {} : { role: id(item.role, true) }), ...(item.variant === undefined ? {} : { variant: id(item.variant) }) }; }
function sizes(value: unknown): readonly (readonly [number, number])[] { if (!Array.isArray(value) || value.length > 32) fail(); return Object.freeze(value.map((entry) => { if (!Array.isArray(entry) || entry.length !== 2) fail(); return Object.freeze([integer(entry[0], 16_384, 1), integer(entry[1], 16_384, 1)] as const); })); }
function qaCase(value: unknown): QaCase {
  const item = record(value); const kind = string(item.kind, 64); const common = ["id", "kind"] as const; const target = ["asset", "family", "role", "variant"] as const; const caseId = id(item.id);
  if (kind === "inventory") { exact(item, [...common, "family"], ["roles"]); return Object.freeze({ id: caseId, kind, family: id(item.family), ...(item.roles === undefined ? {} : { roles: strings(item.roles, 64, (entry) => id(entry, true)) }) }); }
  if (kind === "accessibility") { exact(item, [...common, "requireConsistentLabels"], target); return Object.freeze({ id: caseId, kind, requireConsistentLabels: bool(item.requireConsistentLabels), ...selector(item) }); }
  if (kind === "palette") { exact(item, [...common, "allowedTokens", "allowLiterals"], target); return Object.freeze({ id: caseId, kind, allowedTokens: strings(item.allowedTokens, 256, id), allowLiterals: bool(item.allowLiterals), ...selector(item) }); }
  if (kind === "external-reference") { exact(item, [...common, "forbidExternalUrls", "forbidExternalImages", "forbidExternalUses", "forbidExternalStyles", "forbidExternalFonts"], target); return Object.freeze({ id: caseId, kind, forbidExternalUrls: bool(item.forbidExternalUrls), forbidExternalImages: bool(item.forbidExternalImages), forbidExternalUses: bool(item.forbidExternalUses), forbidExternalStyles: bool(item.forbidExternalStyles), forbidExternalFonts: bool(item.forbidExternalFonts), ...selector(item) }); }
  if (kind === "embedded-content") { exact(item, [...common, "forbidEmbeddedRaster", "forbidEmbeddedFonts"], target); return Object.freeze({ id: caseId, kind, forbidEmbeddedRaster: bool(item.forbidEmbeddedRaster), forbidEmbeddedFonts: bool(item.forbidEmbeddedFonts), ...selector(item) }); }
  if (kind === "recipe") { exact(item, [...common, "verifyProvenance", "verifyReceipts"], ["recipe", "family"]); return Object.freeze({ id: caseId, kind, verifyProvenance: bool(item.verifyProvenance), verifyReceipts: bool(item.verifyReceipts), ...(item.recipe === undefined ? {} : { recipe: id(item.recipe) }), ...(item.family === undefined ? {} : { family: id(item.family) }) }); }
  if (kind === "canvas") { exact(item, [...common, "requireViewbox", "enforceMinimumSize"], target); return Object.freeze({ id: caseId, kind, requireViewbox: bool(item.requireViewbox), enforceMinimumSize: bool(item.enforceMinimumSize), ...selector(item) }); }
  const visual = [...common, "sizes", "backgrounds"] as const; const backgrounds = strings(item.backgrounds, 16, (entry) => { const text = string(entry, 256); if (!(text === "transparent" || /^#[0-9A-F]{8}$/u.test(text) || /^token:[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/u.test(text))) fail(); return text; }); const shared = { id: caseId, sizes: sizes(item.sizes), backgrounds, ...selector(item) };
  if (kind === "pixel-bounds" || kind === "transparent-bounds") { exact(item, [...visual, "alphaThreshold"], target); return Object.freeze({ ...shared, kind, alphaThreshold: integer(item.alphaThreshold, 255) }); }
  if (kind === "clipping") { exact(item, [...visual, "forbiddenEdgePixels"], target); return Object.freeze({ ...shared, kind, forbiddenEdgePixels: integer(item.forbiddenEdgePixels, 16_384) }); }
  if (kind === "visible-padding") { exact(item, visual, [...target, "minimumPaddingPx", "minimumPaddingToken", "minimumPaddingRatio"]); return Object.freeze({ ...shared, kind, ...(item.minimumPaddingPx === undefined ? {} : { minimumPaddingPx: integer(item.minimumPaddingPx, 16_384) }), ...(item.minimumPaddingToken === undefined ? {} : { minimumPaddingToken: id(item.minimumPaddingToken) }), ...(item.minimumPaddingRatio === undefined ? {} : { minimumPaddingRatio: integer(item.minimumPaddingRatio, 1_000_000) }) }); }
  if (kind === "small-size-visibility") { exact(item, visual, [...target, "minimumVisiblePixels", "minimumVisibleRatio"]); return Object.freeze({ ...shared, kind, ...(item.minimumVisiblePixels === undefined ? {} : { minimumVisiblePixels: integer(item.minimumVisiblePixels, 16_777_216) }), ...(item.minimumVisibleRatio === undefined ? {} : { minimumVisibleRatio: integer(item.minimumVisibleRatio, 1_000_000) }) }); }
  if (kind === "baseline") { exact(item, [...visual, "baselineDigest", "rendererId", "rendererVersion", "platformClaim", "canonicalAssetDigest", "svgDigest"], target); return Object.freeze({ ...shared, kind, baselineDigest: digest(item.baselineDigest), rendererId: publicId(item.rendererId), rendererVersion: string(item.rendererVersion, 64), platformClaim: string(item.platformClaim, 64), canonicalAssetDigest: digest(item.canonicalAssetDigest), svgDigest: digest(item.svgDigest) }); }
  return fail();
}

export function validateQaProfilePage(raw: unknown): QaProfilePage {
  return page(unwrap(raw, "qa-profile-page"), (entry) => { const item = exact(entry, ["id", "renderer", "formats", "caseCount", "semanticCaseCount", "visualCaseCount", "baselineCaseCount", "qaDigest", "brandSystemDigest"]); const caseCount = integer(item.caseCount, 512); const semanticCaseCount = integer(item.semanticCaseCount, caseCount); const visualCaseCount = integer(item.visualCaseCount, caseCount); const baselineCaseCount = integer(item.baselineCaseCount, visualCaseCount); if (semanticCaseCount + visualCaseCount !== caseCount) fail(); return Object.freeze({ id: id(item.id), renderer: enumeration(item.renderer, ["optional", "required"]), formats: strings<"html" | "json" | "markdown">(item.formats, 3, (value) => enumeration(value, ["html", "json", "markdown"])), caseCount, semanticCaseCount, visualCaseCount, baselineCaseCount, qaDigest: digest(item.qaDigest), brandSystemDigest: digest(item.brandSystemDigest) }); }, (entry) => entry.id);
}
export function validateQaProfile(raw: unknown): QaProfile {
  const root = exact(unwrap(raw, "qa-profile"), ["profile", "cases", "resolvedTargetCount", "evaluationCount", "qaDigest", "brandSystemDigest", "baselines", "raster"]); if (!Array.isArray(root.cases) || root.cases.length > 512 || !Array.isArray(root.baselines) || root.baselines.length > 256) fail(); const cases = Object.freeze(root.cases.map(qaCase)); orderedUnique(cases.map((entry) => entry.id)); const baselines = Object.freeze(root.baselines.map((entry) => { const item = exact(entry, ["caseId", "digest"]); return Object.freeze({ caseId: id(item.caseId), digest: nullableDigest(item.digest) }); })); orderedUnique(baselines.map((entry) => entry.caseId)); const raster = exact(root.raster, ["available"]); return Object.freeze({ profile: qaProfileDescriptor(root.profile), cases, resolvedTargetCount: integer(root.resolvedTargetCount, 65_536), evaluationCount: integer(root.evaluationCount, 4_096), qaDigest: digest(root.qaDigest), brandSystemDigest: digest(root.brandSystemDigest), baselines, raster: Object.freeze({ available: bool(raster.available) }) });
}

function qaJson(value: unknown): QaJsonValue { return safe(value) as QaJsonValue; }
function diagnostics(value: unknown): readonly QaDiagnostic[] { if (!Array.isArray(value) || value.length > 4_096) fail(); const result = Object.freeze(value.map((entry) => { const item = exact(entry, ["code", "message"], ["location"]); return Object.freeze({ code: publicId(item.code), message: string(item.message, 4_096), ...(item.location === undefined ? {} : { location: string(item.location, 1_024) }) }); })); return result; }
export function validateQaResult(raw: unknown): QaResult {
  const root = exact(unwrap(raw, "qa-result"), ["schema", "schemaVersion", "profileId", "qaDigest", "brandSystemDigest", "status", "exitCode", "counts", "results", "resultDigest"], ["renderer"]); if (root.schema !== "tfsb.brand-qa-result" || root.schemaVersion !== 1 || !Array.isArray(root.results) || root.results.length > 512) fail(); const counts = exact(root.counts, ["pass", "fail", "skipped", "unavailable", "error"]); const typedCounts = Object.freeze({ pass: integer(counts.pass, 512), fail: integer(counts.fail, 512), skipped: integer(counts.skipped, 512), unavailable: integer(counts.unavailable, 512), error: integer(counts.error, 512) }); const status = enumeration(root.status, ["pass", "fail", "skipped", "unavailable", "error"]); const results = Object.freeze(root.results.map((entry) => { const item = exact(entry, ["caseId", "kind", "status", "capability", "capabilityRequired", "measurements", "diagnostics", "evaluations"]); if (!Array.isArray(item.evaluations) || item.evaluations.length > 4_096) fail(); const evaluations = Object.freeze(item.evaluations.map((evaluation) => { const value = exact(evaluation, ["target", "status", "measurements", "diagnostics"], ["width", "height", "background"]); const target = exact(value.target, ["assetId"], ["family", "role", "variant"]); return Object.freeze({ target: Object.freeze({ assetId: id(target.assetId), ...(target.family === undefined ? {} : { family: id(target.family) }), ...(target.role === undefined ? {} : { role: id(target.role, true) }), ...(target.variant === undefined ? {} : { variant: id(target.variant) }) }), ...(value.width === undefined ? {} : { width: integer(value.width, 16_384, 1) }), ...(value.height === undefined ? {} : { height: integer(value.height, 16_384, 1) }), ...(value.background === undefined ? {} : { background: string(value.background, 256) }), status: enumeration(value.status, ["pass", "fail", "skipped", "unavailable", "error"]), measurements: qaJson(value.measurements) as Readonly<Record<string, QaJsonValue>>, diagnostics: diagnostics(value.diagnostics) }); })); return Object.freeze({ caseId: id(item.caseId), kind: string(item.kind, 64), status: enumeration(item.status, ["pass", "fail", "skipped", "unavailable", "error"]), capability: enumeration(item.capability, ["semantic-core-v1", "renderer"]), capabilityRequired: bool(item.capabilityRequired), measurements: qaJson(item.measurements) as Readonly<Record<string, QaJsonValue>>, diagnostics: diagnostics(item.diagnostics), evaluations }); })); orderedUnique(results.map((entry) => entry.caseId));
  let renderer: QaResult["renderer"]; if (root.renderer !== undefined) { const item = exact(root.renderer, ["id", "version", "qualificationId", "platformClaim"]); renderer = Object.freeze({ id: publicId(item.id), version: string(item.version, 64), qualificationId: digest(item.qualificationId), platformClaim: string(item.platformClaim, 64) }); }
  const exitCode = integer(root.exitCode, 3) as 0 | 1 | 2 | 3;
  return Object.freeze({ schema: "tfsb.brand-qa-result", schemaVersion: 1, profileId: id(root.profileId), qaDigest: digest(root.qaDigest), brandSystemDigest: digest(root.brandSystemDigest), status, exitCode, counts: typedCounts, ...(renderer === undefined ? {} : { renderer }), results, resultDigest: digest(root.resultDigest) });
}

function diffValue(value: unknown): DiffValue { return safe(value) as DiffValue; }
function change(value: unknown): DiffChange { const item = exact(value, ["id", "change", "before", "after"]); const kind = enumeration(item.change, ["added", "removed", "changed"]); if ((kind === "added" && item.before !== null) || (kind === "removed" && item.after !== null) || (kind === "changed" && (item.before === null || item.after === null))) fail(); return Object.freeze({ id: string(item.id, 512), change: kind, before: item.before === null ? null : diffValue(item.before), after: item.after === null ? null : diffValue(item.after) }); }
function changes(value: unknown): readonly DiffChange[] { if (!Array.isArray(value) || value.length > 4_096) fail(); const result = Object.freeze(value.map(change)); orderedUnique(result.map((entry) => entry.id)); return result; }
function emptyRecord(value: unknown): boolean { return typeof value === "object" && value !== null && !Array.isArray(value) && Object.keys(value).length === 0; }
export function validateSemanticDiff(raw: unknown): SemanticDiff {
  const root = exact(unwrap(raw, "semantic-diff"), ["diff", "beforeBindingDigest", "afterBindingDigest", "visualDiff"]); const value = exact(root.diff, ["schema", "schemaVersion", "beforeDigest", "afterDigest", "status", "inventory", "bindings", "tokens", "recipes", "derived", "geometry", "qaImpact", "packageAndLegal", "consumerProfiles", "exports", "resultDigest"]); if (value.schema !== "tfsb.brand-diff" || value.schemaVersion !== 1) fail();
  const sections = [value.inventory, value.bindings, value.tokens, value.recipes, value.derived, value.geometry, value.qaImpact, value.packageAndLegal, value.consumerProfiles, value.exports];
  const canonicalPlaceholder = sections.every(emptyRecord);
  if (canonicalPlaceholder && (value.status !== "equal" || value.beforeDigest !== value.afterDigest || root.beforeBindingDigest !== root.afterBindingDigest)) fail();
  const inventory = exact(canonicalPlaceholder ? { families: [], roles: [], variants: [], requirements: [], completeness: null } : value.inventory, ["families", "roles", "variants", "requirements", "completeness"]); const bindings = exact(canonicalPlaceholder ? { records: [] } : value.bindings, ["records"]); const tokens = exact(canonicalPlaceholder ? { records: [] } : value.tokens, ["records"]); const recipes = exact(canonicalPlaceholder ? { records: [], affectedTargets: [] } : value.recipes, ["records", "affectedTargets"]); const derived = exact(canonicalPlaceholder ? { records: [] } : value.derived, ["records"]); const geometry = exact(canonicalPlaceholder ? { records: [], canonicalTypedGeometryChanged: false, equivalenceClaim: "none" } : value.geometry, ["records", "canonicalTypedGeometryChanged", "equivalenceClaim"]); const qa = exact(canonicalPlaceholder ? { profiles: [], cases: [], affectedCases: [] } : value.qaImpact, ["profiles", "cases", "affectedCases"]); const legal = exact(canonicalPlaceholder ? { package: null, companions: [], bundleRelevantChanged: false } : value.packageAndLegal, ["package", "companions", "bundleRelevantChanged"]); const consumers = exact(canonicalPlaceholder ? { beforeState: "unavailable", afterState: "unavailable", status: "unavailable", records: [] } : value.consumerProfiles, ["beforeState", "afterState", "status", "records"]); const exports = exact(canonicalPlaceholder ? { beforeState: "unavailable", afterState: "unavailable", status: "unavailable", records: [] } : value.exports, ["beforeState", "afterState", "status", "records"]); const visual = exact(root.visualDiff, ["available"]);
  return Object.freeze({ diff: Object.freeze({ schema: "tfsb.brand-diff", schemaVersion: 1, beforeDigest: digest(value.beforeDigest), afterDigest: digest(value.afterDigest), status: enumeration(value.status, ["equal", "changed"]), inventory: Object.freeze({ families: changes(inventory.families), roles: changes(inventory.roles), variants: changes(inventory.variants), requirements: changes(inventory.requirements), completeness: inventory.completeness === null ? null : change(inventory.completeness) }), bindings: Object.freeze({ records: changes(bindings.records) }), tokens: Object.freeze({ records: changes(tokens.records) }), recipes: Object.freeze({ records: changes(recipes.records), affectedTargets: strings(recipes.affectedTargets, 128, id) }), derived: Object.freeze({ records: changes(derived.records) }), geometry: Object.freeze({ records: changes(geometry.records), canonicalTypedGeometryChanged: bool(geometry.canonicalTypedGeometryChanged), equivalenceClaim: enumeration(geometry.equivalenceClaim, ["none"]) }), qaImpact: Object.freeze({ profiles: changes(qa.profiles), cases: changes(qa.cases), affectedCases: strings(qa.affectedCases, 512, id) }), packageAndLegal: Object.freeze({ package: legal.package === null ? null : change(legal.package), companions: changes(legal.companions), bundleRelevantChanged: bool(legal.bundleRelevantChanged) }), consumerProfiles: Object.freeze({ beforeState: string(consumers.beforeState, 64), afterState: string(consumers.afterState, 64), status: enumeration(consumers.status, ["available", "unavailable"]), records: changes(consumers.records) }), exports: Object.freeze({ beforeState: string(exports.beforeState, 64), afterState: string(exports.afterState, 64), status: enumeration(exports.status, ["available", "unavailable"]), records: changes(exports.records) }), resultDigest: digest(value.resultDigest) }), beforeBindingDigest: digest(root.beforeBindingDigest), afterBindingDigest: digest(root.afterBindingDigest), visualDiff: Object.freeze({ available: bool(visual.available) }) });
}

function consumerProfile(value: unknown): ConsumerProfile { const item = exact(value, ["id", "qualifiedId", "version", "compatiblePackage", "composes", "parameters", "outputs"], ["minimumBrandVersion", "maximumBrandVersionExclusive"]); if (!Array.isArray(item.parameters) || item.parameters.length > 16 || !Array.isArray(item.outputs) || item.outputs.length > 256) fail(); const parameters = Object.freeze(item.parameters.map((entry) => { const parameter = exact(entry, ["id", "values"]); const values = strings(parameter.values, 16, (part) => string(part, 64)); orderedUnique(values); return Object.freeze({ id: id(parameter.id), values }); })); orderedUnique(parameters.map((entry) => entry.id)); const outputs = Object.freeze(item.outputs.map((entry) => { const output = exact(entry, ["requirement", "collision", "when"], ["asset", "companion", "family", "role", "variant", "destination", "destinationDirectory", "filenamePolicy"]); if (!Array.isArray(output.when) || output.when.length > 16 || output.collision !== "error") fail(); return Object.freeze({ ...(output.asset === undefined ? {} : { asset: id(output.asset) }), ...(output.companion === undefined ? {} : { companion: id(output.companion) }), ...(output.family === undefined ? {} : { family: id(output.family) }), ...(output.role === undefined ? {} : { role: id(output.role, true) }), ...(output.variant === undefined ? {} : { variant: id(output.variant) }), ...(output.destination === undefined ? {} : { destination: string(output.destination, 1_024) }), ...(output.destinationDirectory === undefined ? {} : { destinationDirectory: string(output.destinationDirectory, 1_024) }), ...(output.filenamePolicy === undefined ? {} : { filenamePolicy: enumeration(output.filenamePolicy, ["asset-id.svg", "source-basename"]) }), requirement: enumeration(output.requirement, ["required", "optional"]), collision: "error" as const, when: Object.freeze(output.when.map((entry) => { const when = exact(entry, ["parameter", "equals"]); return Object.freeze({ parameter: id(when.parameter), equals: string(when.equals, 64) }); })) }); })); return Object.freeze({ id: id(item.id), qualifiedId: string(item.qualifiedId, 256), version: integer(item.version, 65_535, 1), compatiblePackage: id(item.compatiblePackage), ...(item.minimumBrandVersion === undefined ? {} : { minimumBrandVersion: string(item.minimumBrandVersion, 64) }), ...(item.maximumBrandVersionExclusive === undefined ? {} : { maximumBrandVersionExclusive: string(item.maximumBrandVersionExclusive, 64) }), composes: strings(item.composes, 4, (entry) => string(entry, 256)), parameters, outputs }); }
export function validateConsumerProfilePage(raw: unknown): ConsumerProfilePage { return page(unwrap(raw, "consumer-profile-page"), (entry) => { const item = exact(entry, ["qualifiedProfileId", "authorityKind", "packageId", "profile", "outputRuleCount", "resolvedOutputCount"]); const profile = consumerProfile(item.profile); if (item.qualifiedProfileId !== profile.qualifiedId) fail(); return Object.freeze({ qualifiedProfileId: profile.qualifiedId, authorityKind: enumeration(item.authorityKind, ["producer-project", "producer-package", "consumer-local"]), packageId: id(item.packageId), profile, outputRuleCount: integer(item.outputRuleCount, 256), resolvedOutputCount: item.resolvedOutputCount === null ? null : integer(item.resolvedOutputCount, 256) }); }, (entry) => entry.qualifiedProfileId); }
export function validateConsumerLockStatus(raw: unknown): ConsumerLockStatus { const root = exact(unwrap(raw, "consumer-lock-status"), ["status", "exitCode", "packages", "mappings", "localProfiles"], ["lockDigest", "consumerProjectDigest"]); if (!Array.isArray(root.packages) || root.packages.length > 8 || !Array.isArray(root.mappings) || root.mappings.length > 512) fail(); const status = enumeration(root.status, ["ok", "source-unavailable", "stale", "drift", "collision", "invalid"]); const packages = Object.freeze(root.packages.map((entry) => { const item = exact(entry, ["packageId", "brandVersion", "sourceKind", "profiles"]); if (!Array.isArray(item.profiles) || item.profiles.length > 8) fail(); const profiles = Object.freeze(item.profiles.map((profile) => { const value = exact(profile, ["id", "version", "digest", "parameters"]); const rawParameters = record(value.parameters); if (Object.keys(rawParameters).length > 16) fail(); const parameters: Record<string, string> = {}; for (const key of Object.keys(rawParameters).sort()) parameters[id(key)] = string(rawParameters[key], 64); return Object.freeze({ id: string(value.id, 256), version: integer(value.version, 65_535, 1), digest: digest(value.digest), parameters: Object.freeze(parameters) }); })); return Object.freeze({ packageId: id(item.packageId), brandVersion: string(item.brandVersion, 64), sourceKind: enumeration(item.sourceKind, ["local-bundle", "npm-installed"]), profiles }); })); orderedUnique(packages.map((entry) => entry.packageId)); const mappings = Object.freeze(root.mappings.map((entry) => { const item = exact(entry, ["packageId", "kind", "sourceId", "destination", "expectedDigest", "current"]); return Object.freeze({ packageId: id(item.packageId), kind: enumeration(item.kind, ["asset", "companion"]), sourceId: id(item.sourceId), destination: string(item.destination, 1_024), expectedDigest: digest(item.expectedDigest), current: enumeration(item.current, ["exact", "missing", "different", "unsafe"]) }); })); return Object.freeze({ status, exitCode: integer(root.exitCode, 2) as 0 | 1 | 2, ...(root.lockDigest === undefined ? {} : { lockDigest: digest(root.lockDigest) }), ...(root.consumerProjectDigest === undefined ? {} : { consumerProjectDigest: digest(root.consumerProjectDigest) }), packages, mappings, localProfiles: strings(root.localProfiles, 32, (entry) => string(entry, 256)) }); }

export function validateExportCapability(raw: unknown): ExportCapability { const data = record(unwrap(raw, "export-capability")); if (data.available === false) { exact(data, ["available"]); return Object.freeze({ available: false }); } const root = exact(data, ["available", "adapterId", "rendererPackage", "rendererVersion", "rendererBuildDigest", "nodeMajor", "platformClaim", "qualificationId"]); if (root.available !== true || root.adapterId !== "resvg-png-v1" || root.nodeMajor !== 22 || root.platformClaim !== "darwin-arm64") fail(); return Object.freeze({ available: true, adapterId: "resvg-png-v1", rendererPackage: string(root.rendererPackage, 256), rendererVersion: string(root.rendererVersion, 64), rendererBuildDigest: digest(root.rendererBuildDigest), nodeMajor: 22, platformClaim: "darwin-arm64", qualificationId: digest(root.qualificationId) }); }
function exportStatus(value: unknown): ExportStatus { const item = exact(value, ["profileId", "outputId", "assetId", "binding", "destination", "state", "width", "height", "purpose", "background", "alpha", "canonicalAssetDigest", "svgDigest", "profileDigest", "outputConfigDigest", "pngDigest", "decodedPixelDigest", "receiptDigest", "capabilityAvailable"]); let binding: ExportStatus["binding"] = null; if (item.binding !== null) { const value = exact(item.binding, ["family", "role", "variant"]); binding = Object.freeze({ family: id(value.family), role: id(value.role, true), variant: id(value.variant) }); } return Object.freeze({ profileId: id(item.profileId), outputId: id(item.outputId), assetId: item.assetId === null ? null : id(item.assetId), binding, destination: string(item.destination, 1_024), state: string(item.state, 64), width: item.width === null ? null : integer(item.width, 16_384, 1), height: item.height === null ? null : integer(item.height, 16_384, 1), purpose: item.purpose === null ? null : enumeration(item.purpose, ["png", "apple-touch-icon", "pwa-icon", "avatar", "social-card"]), background: item.background === null ? null : string(item.background, 256), alpha: item.alpha === null ? null : enumeration(item.alpha, ["straight", "opaque"]), canonicalAssetDigest: nullableDigest(item.canonicalAssetDigest), svgDigest: nullableDigest(item.svgDigest), profileDigest: nullableDigest(item.profileDigest), outputConfigDigest: nullableDigest(item.outputConfigDigest), pngDigest: nullableDigest(item.pngDigest), decodedPixelDigest: nullableDigest(item.decodedPixelDigest), receiptDigest: nullableDigest(item.receiptDigest), capabilityAvailable: bool(item.capabilityAvailable) }); }
export function validateExportStatusPage(raw: unknown): ExportStatusPage { return page(unwrap(raw, "export-status-page"), exportStatus, (entry) => `${entry.profileId}\0${entry.outputId}`); }

function artifact(value: unknown, role: VisualRole, width: number, height: number): VisualArtifact { const item = exact(value, ["byteLength", "bytesBase64", "decodedPixelDigest", "encoding", "height", "mediaType", "pngDigest", "role", "width"]); if (item.role !== role || item.mediaType !== "image/png" || item.encoding !== "base64" || item.width !== width || item.height !== height) fail(); const byteLength = integer(item.byteLength, 6_291_456); const bytesBase64 = string(item.bytesBase64, 8_388_608); if (!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/u.test(bytesBase64)) fail(); return Object.freeze({ role, mediaType: "image/png", encoding: "base64", width, height, byteLength, pngDigest: digest(item.pngDigest), decodedPixelDigest: digest(item.decodedPixelDigest), bytesBase64 }); }
function decodeBase64(value: string): Uint8Array { let binary: string; try { binary = atob(value); } catch { return fail(); } const bytes = Uint8Array.from(binary, (character) => character.charCodeAt(0)); let canonical = ""; for (let offset = 0; offset < binary.length; offset += 32_766) canonical += btoa(binary.slice(offset, offset + 32_766)); if (canonical !== value) fail(); return bytes; }
function hex(bytes: ArrayBuffer): string { return [...new Uint8Array(bytes)].map((byte) => byte.toString(16).padStart(2, "0")).join(""); }
function canonicalJson(value: DecoderValue): string { if (Array.isArray(value)) return `[${value.map(canonicalJson).join(",")}]`; if (value !== null && typeof value === "object") { const item = value as { readonly [key: string]: DecoderValue }; return `{${Object.keys(item).sort().map((key) => `${JSON.stringify(key)}:${canonicalJson(item[key] as DecoderValue)}`).join(",")}}`; } return JSON.stringify(value); }
export async function validateVisualEvidence(raw: unknown): Promise<VisualEvidence> {
  const data = exact(unwrap(raw, "visual-evidence"), ["schema", "schemaVersion", "kind", "projectDigest", "brandSystemDigest", "target", "configuration", "renderer", "artifacts", "evidenceDigest"], ["sourceDigest", "qaDigest", "difference"]); if (data.schema !== "tfsb.studio-visual-evidence" || data.schemaVersion !== 1) fail(); const kind = enumeration(data.kind, ["project-render", "qa-baseline", "brand-diff"]); const isProject = kind === "project-render", isQa = kind === "qa-baseline", isDiff = kind === "brand-diff"; if ((isProject && (data.sourceDigest !== undefined || data.qaDigest !== undefined || data.difference !== undefined)) || (isQa && (data.qaDigest === undefined || data.sourceDigest !== undefined || data.difference === undefined)) || (isDiff && (data.sourceDigest === undefined || data.qaDigest !== undefined || data.difference === undefined))) fail();
  const configuration = exact(data.configuration, ["background", "height", "width"]); const width = integer(configuration.width, 1_024, 16), height = integer(configuration.height, 1_024, 16); if (width * height > 1_048_576) fail(); const background = string(configuration.background, 256); if (!(background === "transparent" || /^#[0-9A-F]{8}$/u.test(background) || /^token:[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/u.test(background))) fail();
  const targetValue = exact(data.target, ["assetId", "canonicalAssetDigest", "svgDigest"], ["binding"]); let binding: VisualEvidence["target"]["binding"]; if (targetValue.binding !== undefined) { const value = exact(targetValue.binding, ["family", "role", "variant"]); binding = Object.freeze({ family: id(value.family), role: id(value.role, true), variant: id(value.variant) }); }
  const rendererValue = exact(data.renderer, ["id", "platformClaim", "qualificationId", "version"]); if (rendererValue.id !== "resvg-png-v1" || rendererValue.version !== "2.6.2" || rendererValue.qualificationId !== QUALIFIED_RASTER_ID || rendererValue.platformClaim !== "darwin-arm64") fail(); const roles = isProject ? ["current"] as const : isQa ? ["baseline", "current"] as const : ["before", "after"] as const; if (!Array.isArray(data.artifacts) || data.artifacts.length !== roles.length) fail(); const artifacts = Object.freeze(data.artifacts.map((entry, index) => artifact(entry, roles[index] as VisualRole, width, height))); let aggregate = 0;
  for (const entry of artifacts) { const bytes = decodeBase64(entry.bytesBase64); aggregate += bytes.byteLength; if (bytes.byteLength < 24 || bytes.byteLength !== entry.byteLength || ![137,80,78,71,13,10,26,10].every((byte, index) => bytes[index] === byte) || `sha256:${hex(await crypto.subtle.digest("SHA-256", Uint8Array.from(bytes).buffer))}` !== entry.pngDigest) fail(); const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength); if (view.getUint32(16) !== width || view.getUint32(20) !== height) fail(); }
  if (aggregate > 8_388_608) fail(); let difference: VisualEvidence["difference"]; if (!isProject) { const value = exact(data.difference, ["changedBounds", "changedPixels", "claim", "maximumChannelDelta"]); const changedPixels = integer(value.changedPixels, width * height), maximumChannelDelta = integer(value.maximumChannelDelta, 255); const equal = changedPixels === 0; if (value.claim !== (equal ? "pixel-equal-for-this-renderer-and-case-only" : "pixel-different-for-this-renderer-and-case-only") || (equal && (value.changedBounds !== null || maximumChannelDelta !== 0)) || (!equal && (value.changedBounds === null || maximumChannelDelta === 0))) fail(); let changedBounds: NonNullable<VisualEvidence["difference"]>["changedBounds"] = null; if (value.changedBounds !== null) { const bounds = exact(value.changedBounds, ["bottom", "left", "right", "top"]); changedBounds = Object.freeze({ left: integer(bounds.left, width - 1), top: integer(bounds.top, height - 1), right: integer(bounds.right, width - 1), bottom: integer(bounds.bottom, height - 1) }); if (changedBounds.left > changedBounds.right || changedBounds.top > changedBounds.bottom) fail(); } difference = Object.freeze({ changedPixels, maximumChannelDelta, changedBounds, claim: value.claim as NonNullable<VisualEvidence["difference"]>["claim"] }); }
  if (new TextEncoder().encode(JSON.stringify(data)).byteLength > 12_582_912) fail(); const projection = safe(data) as { readonly [key: string]: DecoderValue }; const { evidenceDigest: omitted, ...withoutDigest } = projection; void omitted; const projectedArtifacts = artifacts.map(({ bytesBase64: omittedBytes, ...entry }) => { void omittedBytes; return entry as unknown as DecoderValue; }); const basis = new TextEncoder().encode(`tfsb.studio-visual-evidence-v1\n${canonicalJson({ ...withoutDigest, artifacts: projectedArtifacts } as DecoderValue)}`); const evidenceDigest = digest(data.evidenceDigest); if (`sha256:${hex(await crypto.subtle.digest("SHA-256", basis))}` !== evidenceDigest) fail();
  return Object.freeze({ schema: "tfsb.studio-visual-evidence", schemaVersion: 1, kind, projectDigest: digest(data.projectDigest), brandSystemDigest: digest(data.brandSystemDigest), ...(data.sourceDigest === undefined ? {} : { sourceDigest: digest(data.sourceDigest) }), ...(data.qaDigest === undefined ? {} : { qaDigest: digest(data.qaDigest) }), target: Object.freeze({ assetId: id(targetValue.assetId), canonicalAssetDigest: digest(targetValue.canonicalAssetDigest), svgDigest: digest(targetValue.svgDigest), ...(binding === undefined ? {} : { binding }) }), configuration: Object.freeze({ width, height, background }), renderer: Object.freeze({ id: "resvg-png-v1", version: "2.6.2", qualificationId: QUALIFIED_RASTER_ID, platformClaim: "darwin-arm64" }), artifacts, ...(difference === undefined ? {} : { difference }), evidenceDigest });
}
