use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

fn quoted_commands(text: &str) -> Vec<String> {
    text.split('"')
        .skip(1)
        .step_by(2)
        .filter(|s| {
            s.starts_with("studio_") && s.bytes().all(|c| c.is_ascii_lowercase() || c == b'_')
        })
        .map(str::to_owned)
        .collect()
}

#[test]
fn handlers_inventory_permissions_and_scene_bridge_agree() -> Result<(), Box<dyn std::error::Error>>
{
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let inventory = quoted_commands(&fs::read_to_string(root.join("src/command_inventory.rs"))?);
    let expected: BTreeSet<_> = inventory.iter().cloned().collect();
    assert_eq!(expected.len(), inventory.len(), "duplicate native command");
    assert_eq!(
        expected.len(),
        42,
        "unexplained change from the 24 + 18 command plan"
    );
    let lib = fs::read_to_string(root.join("src/lib.rs"))?;
    let handler = lib
        .split("tauri::generate_handler![")
        .nth(1)
        .ok_or("handler absent")?
        .split("])")
        .next()
        .ok_or("handler terminator absent")?;
    let handlers: Vec<_> = handler
        .split(',')
        .filter_map(|s| s.trim().rsplit("::").next())
        .filter(|s| !s.is_empty())
        .map(str::to_owned)
        .collect();
    let handler_set: BTreeSet<_> = handlers.iter().cloned().collect();
    assert_eq!(handler_set.len(), handlers.len(), "duplicate handler");
    assert_eq!(expected, handler_set);
    #[derive(serde::Deserialize)]
    struct Capability {
        permissions: Vec<String>,
        windows: Vec<String>,
    }
    let capability: Capability =
        serde_json::from_str(&fs::read_to_string(root.join("capabilities/main.json"))?)?;
    assert_eq!(capability.windows, ["main"]);
    let permissions: BTreeSet<_> = capability
        .permissions
        .iter()
        .map(|p| p.strip_prefix("allow-").unwrap_or(p).replace('-', "_"))
        .collect();
    assert_eq!(
        permissions.len(),
        capability.permissions.len(),
        "duplicate permission"
    );
    assert_eq!(expected, permissions);
    for command in &expected {
        let permission =
            fs::read_to_string(root.join(format!("permissions/autogenerated/{command}.toml")))?;
        assert!(permission.contains(&format!("commands.allow = [\"{command}\"]")));
    }
    let bridge =
        fs::read_to_string(root.join("../src/features/vector-graphics/vector-graphics-bridge.ts"))?;
    let bridge_commands = quoted_commands(&bridge);
    let scene_expected: BTreeSet<_> = expected
        .iter()
        .filter(|n| n.starts_with("studio_scene_"))
        .cloned()
        .collect();
    assert_eq!(bridge_commands.len(), scene_expected.len());
    assert_eq!(
        bridge_commands.into_iter().collect::<BTreeSet<_>>(),
        scene_expected
    );
    Ok(())
}

#[test]
fn negative_inventory_checks_reject_anomalies() -> Result<(), Box<dyn std::error::Error>> {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let inventory = quoted_commands(&fs::read_to_string(root.join("src/command_inventory.rs"))?);
    let inventory_set: BTreeSet<_> = inventory.iter().cloned().collect();

    // 1. Unknown command is not in inventory
    assert!(!inventory_set.contains("studio_unknown_command_xyz"));

    // 2. Duplicate detection: duplicate in command list causes length mismatch
    let mut duplicated = inventory.clone();
    duplicated.push(inventory[0].clone());
    let dup_set: BTreeSet<_> = duplicated.iter().cloned().collect();
    assert_ne!(
        dup_set.len(),
        duplicated.len(),
        "duplicate command must be detected"
    );

    // 3. Handler-only anomaly: handler present that is absent in inventory
    let mut simulated_handlers = inventory_set.clone();
    simulated_handlers.insert("studio_rogue_handler".to_string());
    assert_ne!(
        inventory_set, simulated_handlers,
        "handler-only anomaly must not match inventory"
    );

    // 4. Inventory-only anomaly: inventory present that is absent in handlers
    let mut simulated_inventory = inventory_set.clone();
    simulated_inventory.insert("studio_unhandled_command".to_string());
    assert_ne!(
        simulated_inventory, inventory_set,
        "inventory-only anomaly must not match handlers"
    );

    // 5. Permission-missing anomaly: nonexistent permission file fails to read
    let bogus_perm_path = root.join("permissions/autogenerated/studio_bogus_missing.toml");
    assert!(
        fs::read_to_string(&bogus_perm_path).is_err(),
        "missing permission file must error on read"
    );

    Ok(())
}
