import { useEffect, useMemo, useState } from "react";
import type { Proposal } from "../../design-evidence/types";
import type { ExportStatusPage } from "../../brand-read/StudioBrandReadClient";
import type { StudioBrandPlanStartRequest } from "../../brand-plans/contracts";

export function ExportPlanForm({ projectHandle, status, available, disabled, prefill, onCreate }: { readonly projectHandle: string; readonly status: ExportStatusPage; readonly available: boolean; readonly disabled: boolean; readonly prefill?: Extract<Proposal, { readonly kind: "export" }> | undefined; readonly onCreate: (request: StudioBrandPlanStartRequest) => void }) {
  const profiles = useMemo(() => [...new Set(status.page.items.map((item) => item.profileId))].sort(), [status]); const [profileId, setProfileId] = useState(""); const [whole, setWhole] = useState(true); const [outputs, setOutputs] = useState<readonly string[]>([]); const choices = status.page.items.filter((item) => item.profileId === profileId); const toggle = (id: string) => setOutputs((current) => current.includes(id) ? current.filter((entry) => entry !== id) : [...current, id].sort());
  useEffect(() => { if (!prefill) return; setProfileId(profiles.includes(prefill.profileId) ? prefill.profileId : ""); setWhole(prefill.outputIds === undefined); setOutputs((prefill.outputIds ?? []).filter((id) => status.page.items.some((item) => item.profileId === prefill.profileId && item.outputId === id))); }, [prefill, profiles, status]);
  if (!available) return <p className="empty-state">Raster export planning is unavailable without the exact qualified raster capability.</p>;
  return <fieldset disabled={disabled}><legend>Create a typed raster export plan</legend><label>Explicit profile <select value={profileId} onChange={(event) => { setProfileId(event.target.value); setOutputs([]); }}><option value="">Select a profile</option>{profiles.map((profile) => <option key={profile}>{profile}</option>)}</select></label><label><input type="radio" name="export-scope" checked={whole} onChange={() => setWhole(true)} /> Entire selected profile</label><label><input type="radio" name="export-scope" checked={!whole} onChange={() => setWhole(false)} /> Exact output subset</label>{!whole ? <ul>{choices.map((output) => <li key={output.outputId}><label><input type="checkbox" checked={outputs.includes(output.outputId)} onChange={() => toggle(output.outputId)} /> <code>{output.outputId}</code> → <code>{output.destination}</code></label></li>)}</ul> : null}<button type="button" disabled={!profileId || (!whole && outputs.length === 0)} onClick={() => onCreate({ kind: "create-export", projectHandle, profileId, ...(whole ? {} : { outputIds: outputs }) })}>Review export plan</button></fieldset>;
}
