import { createRoot } from "react-dom/client";
import type {
  BrandStatus, ConsumerLockStatus, ConsumerProfilePage, ExportCapability, ExportStatusPage,
  FamilyPage, QaProfile, QaProfilePage, QaResult, RecipeGraph, SemanticDiff, Sha256Digest,
  StudioBrandReadClient, TokenPage, VisualArtifact, VisualEvidence, VisualEvidenceRequest,
} from "./brand-read/StudioBrandReadClient";
import { BrandWorkbench } from "./features/brand-workbench/BrandWorkbench";
import type { StudioBrandPlanClient } from "./brand-plans/StudioBrandPlanClient";
import type { StudioHostStatus, StudioProjectOpen, StudioSourceOpen } from "./protocol/contracts";
import type { DesignPacketClient } from "./design-evidence/client";
import type { BriefPacket, CandidatePacket, DesignEvidencePacket, ReviewPacket } from "./design-evidence/types";
import { DesignExchange } from "./features/design-exchange/DesignExchange";
import briefExample from "../protocol/tfsb-design-evidence-v1/examples/brief.json";
import candidateAExample from "../protocol/tfsb-design-evidence-v1/examples/candidate-a.json";
import candidateBExample from "../protocol/tfsb-design-evidence-v1/examples/candidate-b.json";
import reviewExample from "../protocol/tfsb-design-evidence-v1/examples/review.json";
import { ThemeLab } from "./features/theme-lab/ThemeLab";
import { MockThemeLabBridge } from "./features/theme-lab/test/mock-bridge";
import "./styles/studio.css";

const sha = (digit: string): Sha256Digest => `sha256:${digit.repeat(64)}` as Sha256Digest;
const page = <T,>(items: readonly T[], nextCursor: string | null = null) => ({ page: { size: 64, count: items.length, items, nextCursor }, viewDigest: sha("9") });
const status: BrandStatus = { present: true, schemaVersion: 1, brandDigest: sha("1"), brandSystemDigest: sha("2"), domains: [{ domain: "families", state: "available", digest: sha("3") }, { domain: "qa", state: "available", digest: sha("4") }], counts: { families: 1, roles: 2, variants: 1, bindings: 1, requirements: 1, tokens: 4, recipes: 1, qaProfiles: 1, qaCases: 1, qaBaselines: 1, consumerProfiles: 1, exportProfiles: 1 }, completeness: { satisfied: true, familyCount: 1, variantCount: 1, bindingCount: 1, requirementCount: 1 }, derived: { current: 1, stale: 0 }, consumerLock: { present: true, status: "ok", packages: 1, profiles: 1, mappings: 1 }, export: { outputs: 1, receipts: 1 }, raster: { available: true } };
const familyItems: FamilyPage["page"]["items"] = [{ id: "terminal-nova", name: "Terminal Nova", requiredRoles: ["primary"], optionalRoles: ["monochrome"], variants: [{ family: "terminal-nova", id: "default", backgrounds: ["transparent", "dark"], colorMode: "full-color", scale: "standard", status: "primary", minimumWidthPx: 16, minimumHeightPx: 16 }], bindings: [{ family: "terminal-nova", role: "primary", variant: "default", asset: "brand-mark", authority: "source" }], requirements: [{ family: "terminal-nova", role: "primary", background: "transparent" }], complete: true }];
const families: FamilyPage = page(familyItems);
const tokens: TokenPage = page([{ id: "ink", type: "color", value: "#2A165AFF", referenceCount: 3, recipeUseCount: 1, unused: false }, { id: "accent", type: "gradient", kind: "linear", units: "object-bounding-box-millionth", x1: 0, y1: 0, x2: 1_000_000, y2: 0, stops: [{ offset: 0, color: "#F6C65BFF" }, { offset: 1_000_000, color: "#8F7CFFFF" }], referenceCount: 1, recipeUseCount: 1, unused: false }, { id: "space", type: "dimension", unit: "px", value: 16, referenceCount: 0, recipeUseCount: 0, unused: true }, { id: "muted", type: "opacity", value: 650_000, referenceCount: 2, recipeUseCount: 0, unused: false }]);
const graph: RecipeGraph = { recipeDigest: sha("4"), graphDigest: sha("5"), nodes: [{ recipeId: "derive-mark", sourceAsset: "brand-source", targetAsset: "brand-mark", dependencies: [], dependents: [], operations: ["normalize", "recolor"], operationDigest: sha("6"), depth: 1, targetState: "current", receiptDigest: sha("7") }], affectedTargetCount: 1, ownershipConflicts: 0 };
const qaProfiles: QaProfilePage = page([{ id: "release", renderer: "required", formats: ["html", "json"], caseCount: 1, semanticCaseCount: 0, visualCaseCount: 1, baselineCaseCount: 1, qaDigest: sha("3"), brandSystemDigest: sha("4") }]);
const qaProfile: QaProfile = { profile: { id: "release", renderer: "required", formats: ["html", "json"], cases: ["baseline-mark"] }, cases: [{ id: "baseline-mark", kind: "baseline", asset: "brand-mark", sizes: [[64, 64]], backgrounds: ["transparent"], baselineDigest: sha("5"), rendererId: "resvg-png-v1", rendererVersion: "2.6.2", platformClaim: "darwin-arm64", canonicalAssetDigest: sha("6"), svgDigest: sha("7") }], resolvedTargetCount: 1, evaluationCount: 1, qaDigest: sha("3"), brandSystemDigest: sha("4"), baselines: [{ caseId: "baseline-mark", digest: sha("5") }], raster: { available: true } };
const qaResult: QaResult = { schema: "tfsb.brand-qa-result", schemaVersion: 1, profileId: "release", qaDigest: sha("3"), brandSystemDigest: sha("4"), status: "pass", exitCode: 0, counts: { pass: 1, fail: 0, skipped: 0, unavailable: 0, error: 0 }, results: [{ caseId: "baseline-mark", kind: "baseline", status: "pass", capability: "renderer", capabilityRequired: true, measurements: { changedPixels: 0 }, diagnostics: [{ code: "baseline-current", message: "The exact baseline matches the current render." }], evaluations: [{ target: { assetId: "brand-mark" }, width: 64, height: 64, background: "transparent", status: "pass", measurements: { changedPixels: 0 }, diagnostics: [] }] }], resultDigest: sha("8") };
const change = { id: "terminal-nova/primary/default", change: "changed" as const, before: { asset: "brand-mark", family: "terminal-nova", role: "primary", variant: "default", state: "before" }, after: { asset: "brand-mark", family: "terminal-nova", role: "primary", variant: "default", state: "after" } };
const semanticDiff: SemanticDiff = { diff: { schema: "tfsb.brand-diff", schemaVersion: 1, beforeDigest: sha("1"), afterDigest: sha("2"), status: "changed", inventory: { families: [], roles: [], variants: [], requirements: [], completeness: null }, bindings: { records: [change] }, tokens: { records: [] }, recipes: { records: [], affectedTargets: ["brand-mark"] }, derived: { records: [] }, geometry: { records: [], canonicalTypedGeometryChanged: false, equivalenceClaim: "none" }, qaImpact: { profiles: [], cases: [], affectedCases: ["baseline-mark"] }, packageAndLegal: { package: null, companions: [], bundleRelevantChanged: true }, consumerProfiles: { beforeState: "available", afterState: "available", status: "available", records: [] }, exports: { beforeState: "available", afterState: "available", status: "available", records: [] }, resultDigest: sha("3") }, beforeBindingDigest: sha("4"), afterBindingDigest: sha("5"), visualDiff: { available: true } };
const consumerProfiles: ConsumerProfilePage = page([{ qualifiedProfileId: "terminal-nova/default", authorityKind: "producer-project", packageId: "terminal-nova", profile: { id: "default", qualifiedId: "terminal-nova/default", version: 1, compatiblePackage: "terminal-nova", minimumBrandVersion: "1.0.0", maximumBrandVersionExclusive: "2.0.0", composes: [], parameters: [{ id: "mode", values: ["dark", "light"] }], outputs: [{ asset: "brand-mark", destination: "public/brand-mark.svg", requirement: "required", collision: "error", when: [] }] }, outputRuleCount: 1, resolvedOutputCount: 1 }]);
const consumerLock: ConsumerLockStatus = { status: "ok", exitCode: 0, lockDigest: sha("4"), consumerProjectDigest: sha("5"), packages: [{ packageId: "terminal-nova", brandVersion: "1.0.0", sourceKind: "local-bundle", profiles: [{ id: "default", version: 1, digest: sha("6"), parameters: { mode: "dark" } }] }], mappings: [{ packageId: "terminal-nova", kind: "asset", sourceId: "brand-mark", destination: "public/brand-mark.svg", expectedDigest: sha("7"), current: "exact" }], localProfiles: ["terminal-nova/default"] };
const exportCapability: ExportCapability = { available: true, adapterId: "resvg-png-v1", rendererPackage: "@resvg/resvg-js", rendererVersion: "2.6.2", rendererBuildDigest: sha("1"), nodeMajor: 22, platformClaim: "darwin-arm64", qualificationId: sha("4") };
const exportStatus: ExportStatusPage = page([{ profileId: "app-icons", outputId: "touch-icon", assetId: "brand-mark", binding: null, destination: "public/apple-touch-icon.png", state: "current", width: 180, height: 180, purpose: "apple-touch-icon", background: "#FFFFFFFF", alpha: "opaque", canonicalAssetDigest: sha("1"), svgDigest: sha("2"), profileDigest: sha("3"), outputConfigDigest: sha("4"), pngDigest: sha("5"), decodedPixelDigest: sha("6"), receiptDigest: sha("7"), capabilityAvailable: true }]);

function empty<T>(): ReturnType<typeof page<T>> { return page<T>([]); }
function domainError(): never { throw { reasonCode: "domain-unavailable" }; }
async function artifact(role: VisualArtifact["role"], width: number, height: number): Promise<VisualArtifact> { const bytes = new Uint8Array(48_000); bytes.set([137,80,78,71,13,10,26,10,0,0,0,13,73,72,68,82]); const view = new DataView(bytes.buffer); view.setUint32(16, width); view.setUint32(20, height); let binary = ""; for (let index = 0; index < bytes.length; index += 8_192) binary += String.fromCharCode(...bytes.subarray(index, index + 8_192)); const digest = await crypto.subtle.digest("SHA-256", bytes); return { role, mediaType: "image/png", encoding: "base64", width, height, byteLength: bytes.length, pngDigest: `sha256:${[...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join("")}` as Sha256Digest, decodedPixelDigest: sha("8"), bytesBase64: btoa(binary) }; }
async function evidence(request: VisualEvidenceRequest): Promise<VisualEvidence> { const qa = request.kind === "qa-baseline", diff = request.kind === "brand-diff"; const width = qa ? 64 : request.width, height = qa ? 64 : request.height; const roles: VisualArtifact["role"][] = qa ? ["baseline", "current"] : diff ? ["before", "after"] : ["current"]; const target = qa ? { assetId: "brand-mark", canonicalAssetDigest: sha("1"), svgDigest: sha("2") } : request.target.kind === "asset" ? { assetId: request.target.assetId, canonicalAssetDigest: sha("1"), svgDigest: sha("2") } : { assetId: "brand-mark", canonicalAssetDigest: sha("1"), svgDigest: sha("2"), binding: { family: request.target.family, role: request.target.role, variant: request.target.variant } }; return { schema: "tfsb.studio-visual-evidence", schemaVersion: 1, kind: request.kind, projectDigest: sha("3"), brandSystemDigest: sha("4"), ...(diff ? { sourceDigest: sha("5") } : {}), ...(qa ? { qaDigest: sha("6") } : {}), target, configuration: { width, height, background: qa ? "transparent" : request.background }, renderer: { id: "resvg-png-v1", version: "2.6.2", qualificationId: sha("4"), platformClaim: "darwin-arm64" }, artifacts: await Promise.all(roles.map((role) => artifact(role, width, height))), ...((qa || diff) ? { difference: { changedPixels: 0, maximumChannelDelta: 0, changedBounds: null, claim: "pixel-equal-for-this-renderer-and-case-only" as const } } : {}), evidenceDigest: sha("7") }; }

const scenario = new URLSearchParams(location.search).get("scenario") ?? "populated";
let staleAttempted = false;
const client: StudioBrandReadClient = {
  async getAssetIdentity(_projectHandle, assetId) { return { assetId, canonicalAssetDigest: sha("1"), svgDigest: sha("2") }; },
  async getBrandStatus() { if (scenario === "error") return domainError(); return scenario === "empty" ? { present: false, raster: { available: false } } : scenario.startsWith("exchange") ? { ...status, brandSystemDigest: sha("0") } : status; },
  async listFamilies(_handle, _size, cursor) { if (scenario === "error") return domainError(); if (scenario === "empty") return empty(); if (scenario === "stale" && cursor) { staleAttempted = true; throw { reasonCode: "cursor-stale" }; } return scenario === "stale" && !staleAttempted ? page(familyItems, "stale-cursor") : families; },
  async listTokens() { if (scenario === "error") return domainError(); return scenario === "empty" ? empty() : tokens; },
  async getRecipeGraph() { if (scenario === "error") return domainError(); return scenario === "empty" ? { ...graph, nodes: [], affectedTargetCount: 0 } : scenario.startsWith("exchange") ? { ...graph, nodes: graph.nodes.map((node) => ({ ...node, recipeId: "mark-small" })) } : graph; },
  async listQaProfiles() { if (scenario === "error") return domainError(); return scenario === "empty" ? empty() : qaProfiles; },
  async getQaProfile() { return qaProfile; }, async getQaResult() { return qaResult; },
  async getSemanticDiff() { if (scenario === "error") return domainError(); return semanticDiff; },
  async listConsumerProfiles() { if (scenario === "error") return domainError(); return scenario === "empty" ? empty() : consumerProfiles; },
  async getConsumerLockStatus() { return consumerLock; }, async getExportCapability() { return scenario === "unavailable" ? { available: false } : exportCapability; },
  async listExportStatus() { if (scenario === "error") return domainError(); return scenario === "empty" ? empty() : exportStatus; }, async getVisualEvidence(request) { return evidence(request); },
};
const host: StudioHostStatus = { schemaVersion: 1, studioVersion: "0.1.0", manifestDigest: "a".repeat(64), state: "ready", selectedProtocolVersion: "1.2", serverVersion: "0.1.0", methods: [], capabilities: null, raster: { available: scenario !== "unavailable", qualificationIdentity: scenario === "unavailable" ? null : sha("4") }, projectOpenCount: 1, sourceOpenCount: 1, lastReasonCode: null };
const project: StudioProjectOpen = { projectHandle: "project_fixture", rootKind: "project", schemaVersion: 2, name: "Terminal Nova", canonicalDigest: sha("3"), assetCount: 2, companionCount: 0, state: null };
const source: StudioSourceOpen = { sourceHandle: "source_fixture", rootKind: "source", sourceKind: null, authorityKind: "brand-bundle", digest: sha("4"), packageId: "terminal-nova", brandVersion: "1.0.0", brandSystemDigest: sha("5"), candidateCount: null, profileCount: 1, assetCount: 2, companionCount: 0 };
const packetProject: StudioProjectOpen = scenario.startsWith("exchange") ? { ...project, canonicalDigest: sha("0") } : project;
const brief = briefExample as unknown as BriefPacket;
const candidateA = candidateAExample as unknown as CandidatePacket;
const candidateB = candidateBExample as unknown as CandidatePacket;
const review = reviewExample as unknown as ReviewPacket;
let candidateImport = 0;
const packetClient: DesignPacketClient = {
  async importPacket(expectedKind) {
    if (scenario === "exchange-invalid") return { cancelled: false, kind: "brief", digest: sha("0"), byteCount: 2, packet: {} as DesignEvidencePacket };
    const packet = expectedKind === "brief" ? brief : expectedKind === "review" ? review : candidateImport++ === 0 ? candidateA : candidateB;
    return { cancelled: false, kind: packet.schema === "tfsb.design-brief" ? "brief" : packet.schema === "tfsb.design-candidate" ? "candidate" : "review", digest: packet.schema === "tfsb.design-brief" ? packet.briefDigest : packet.schema === "tfsb.design-candidate" ? packet.candidateDigest : packet.reviewDigest, byteCount: JSON.stringify(packet).length, packet };
  },
  async exportPacket(packet) { return { cancelled: false, kind: packet.schema === "tfsb.design-brief" ? "brief" : packet.schema === "tfsb.design-candidate" ? "candidate" : "review", digest: packet.schema === "tfsb.design-brief" ? packet.briefDigest : packet.schema === "tfsb.design-candidate" ? packet.candidateDigest : packet.reviewDigest, byteCount: JSON.stringify(packet).length }; },
};
let operationSequence = 0;
const planClient: StudioBrandPlanClient = {
  async startPlanOperation(request, onEvent) {
    const operationHandle = `operation_${"b".repeat(64)}`; onEvent({ schemaVersion: 1, sequence: 1, operationHandle, state: "started" });
    if (request.kind === "create-derive") { onEvent({ schemaVersion: 1, sequence: 2, operationHandle, state: "progress", progress: { stage: "validate", completed: 0, total: 1 } }); operationSequence += 1; return { kind: "ready", planHandle: `plan_${operationSequence.toString(16).padStart(64, "0")}`, planDigest: sha("a"), method: "brand.derive.plan", expiresInMs: 600000, projectHandle: project.projectHandle, sourceHandles: [], summary: { selectedRecipes: ["derive-mark"], transitiveRecipes: [], affectedTargets: ["brand-mark"], createdCount: 0, updatedCount: 1, unchangedCount: 0, operationSummaries: [{ recipeId: "derive-mark", targetAssetId: "brand-mark", operations: ["normalize", "recolor"] }], targetStates: [{ targetAssetId: "brand-mark", recipeId: "derive-mark", state: "update", oldDigest: sha("1"), newDigest: sha("2"), newSvgDigest: sha("3") }], tokenDigest: sha("4"), recipeDigest: sha("5"), brandSystemDigest: sha("6"), warnings: ["Review the exact destination."], dryRun: true } }; }
    if (request.kind === "create-qa-baseline") { operationSequence += 1; return { kind: "ready", planHandle: `plan_${operationSequence.toString(16).padStart(64, "0")}`, planDigest: sha("a"), method: "brand.qa.baseline.plan", expiresInMs: 600000, projectHandle: project.projectHandle, sourceHandles: [], summary: { profileId: request.profileId, caseId: request.caseId, baselinePath: "baselines/release/baseline-mark.png", state: "update", oldBaselineDigest: sha("1"), newBaselineDigest: sha("2"), oldQaDigest: sha("3"), newQaDigest: sha("4"), renderer: { id: "resvg-png-v1", version: "2.6.2", qualificationId: "sha256:4bb08e677b87ef1ca74c35c5c22f547cebef4c22a1f98a08a9246fd9397d0f11", platformClaim: "darwin-arm64", rendererBuildDigest: "sha256:22bf6e9f9a100d972da0411a69c5ba504367fc1fa87b3b64e3f35e53926d2d70" }, assetDigests: { old: sha("1"), next: sha("2") }, svgDigests: { old: sha("3"), next: sha("4") }, brandSystemDigests: { old: sha("5"), next: sha("6") }, rasterDifference: { changedPixels: 12, maximumChannelDelta: 4, changedBounds: { left: 1, top: 1, right: 4, bottom: 4 }, beforeDecodedPixelDigest: sha("7"), afterDecodedPixelDigest: sha("8") } } }; }
    if (request.kind === "create-consumer-install" || request.kind === "create-consumer-sync") { const install = request.kind === "create-consumer-install"; operationSequence += 1; return { kind: "ready", planHandle: `plan_${operationSequence.toString(16).padStart(64, "0")}`, planDigest: sha("a"), method: install ? "brand.consumer.install.plan" : "brand.consumer.sync.plan", expiresInMs: 600000, projectHandle: project.projectHandle, sourceHandles: [...request.sourceHandles], summary: { operation: install ? "install" : "sync", packages: ["terminal-nova"], profiles: install ? ["terminal-nova/default"] : [], outputs: [{ kind: "asset", packageId: "terminal-nova", sourceId: "brand-mark", destination: "public/brand-mark.svg", byteDigest: sha("1") }], omittedOptional: [], lockDigest: sha("2") } }; }
    if (request.kind === "create-export") { operationSequence += 1; return { kind: "ready", planHandle: `plan_${operationSequence.toString(16).padStart(64, "0")}`, planDigest: sha("a"), method: "brand.export.plan", expiresInMs: 600000, projectHandle: project.projectHandle, sourceHandles: [], summary: { profileId: request.profileId, adapter: { adapterId: "resvg-png-v1", companionPackage: "@knowledge-forge-ai/tfsb-raster-resvg", companionVersion: "0.0.0-tfsb47f", backend: "wasm", rendererPackage: "@resvg/resvg-wasm", rendererVersion: "2.6.2", rendererBuildDigest: "sha256:22bf6e9f9a100d972da0411a69c5ba504367fc1fa87b3b64e3f35e53926d2d70", nodeMajor: 22, platformClaim: "darwin-arm64", qualificationId: "sha256:4bb08e677b87ef1ca74c35c5c22f547cebef4c22a1f98a08a9246fd9397d0f11" }, outputs: [{ profileId: request.profileId, outputId: "touch-icon", assetId: "brand-mark", destination: "public/apple-touch-icon.png", state: "update", width: 180, height: 180, purpose: "apple-touch-icon", fit: "contain-pad", background: "#FFFFFFFF", alpha: "opaque", canonicalAssetDigest: sha("2"), svgDigest: sha("3"), profileDigest: sha("4"), outputConfigDigest: sha("5"), rendererBuildDigest: "sha256:22bf6e9f9a100d972da0411a69c5ba504367fc1fa87b3b64e3f35e53926d2d70", pngDigest: sha("6"), decodedPixelDigest: sha("7"), receiptDigest: sha("8") }], counts: { create: 0, update: 1, unchanged: 0 }, warnings: [] } }; }
    if (request.kind === "apply") return { kind: "applied", method: "brand.derive.plan" };
    return { kind: "discarded" };
  },
  async cancelPlanOperation() { return { accepted: true }; },
};
const root = document.getElementById("root"); if (!root) throw new Error("fixture root missing");
if (scenario === "themelab") {
  createRoot(root).render(<ThemeLab bridge={new MockThemeLabBridge()} />);
} else {
  createRoot(root).render(<><BrandWorkbench client={client} planClient={planClient} host={host} project={project} source={source} sources={[source]}/>{scenario.startsWith("exchange") ? <DesignExchange host={host} project={packetProject} sources={[source]} readClient={client} packetClient={packetClient} onProposalPrefill={() => undefined} /> : null}</>);
}
